{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kairon.databaseSecretName" . }}
  labels:
    {{- include "kairon.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
{{- end }}
